### ISSUE TITLE
Show internet is active toast, only when internet is gone

### ISSUE THREAD

**Issue by fayaz07** [fayaz07/ots#14]

**Comment by fayaz07** [comment]
Hi @shariful2011 
this feature should come from the backend, please give me some time. I will update the package.

Thank you!

**Comment by shariful2011** [comment]
How long is it gonna take for you to update the package?

**Comment by shariful2011** [comment]
Did you updated the package on pub.dev?

**Comment by shariful2011** [comment]
You updated the package on GitHub but not on pub.dev. When will you update it?

**Comment by fayaz07** [comment]
Updated, please check it

**Comment by shariful2011** [comment]
Yes got it, thanks.

**Comment by fayaz07** [comment]
@shariful2011 Thank you for using this package, feel free to star the repo and fork
