### ISSUE TITLE
Internet Connectivity toast showing on app startup though inernet is connected

### ISSUE THREAD

**Issue by shariful2011** [fayaz07/ots#15]
I used your package everything is working correctly but there is a problem when the app starts up the toast Internet is connected
appears but I want it to appear only when connectivity changes. How can I do that?

**Comment by fayaz07** [comment]
Hi @shariful2011 
thank you for your request, I already created an issue regarding this. Please follow up there at #14

**Comment by fayaz07** [comment]
#14
