### ISSUE TITLE
Flutter 2 Null Safety support

### ISSUE THREAD

**Issue by TJMusiitwa** [fayaz07/ots#25]
Hey there,
Are there any plans to get null-safety support for this library?
I am using it as a crucial dependency in my project and due to the "connectivity" package still using old dependencies, it is causing bugs in running pub-update.
Thanks

**Comment by fayaz07** [comment]
Hi @TJMusiitwa 
Thanks for being a user of the package. I will definitely push the null safety update soon.
Thanks

**Comment by TJMusiitwa** [comment]
That would be great or if possible just updating the connectivity package to the earliest version that supports Flutter 2 and having it on a pre null-safe branch that I could use whilst you work behind the scenes would do me wonders.

**Comment by fayaz07** [comment]
Anyhow I should make this stable. I will have to update the docs and push it to latest version directly. I believe there are not many complex things involved.

**Comment by TJMusiitwa** [comment]
Alright kindly push a quick comment here when all is well on your end and I will add it back to my project. You could say it is somewhat the glue holding my project together

**Comment by fayaz07** [comment]
@TJMusiitwa will push the `connectivity` pkg update, `Null safety` to be added later.

**Comment by Pythnist** [comment]
any plans to update package to null safety

**Comment by fayaz07** [comment]
Sure I planned to push the update tomorrow.

**Comment by fayaz07** [comment]
new version is released, [v1.0.0](https://pub.dev/packages/ots)
