### ISSUE TITLE
RenderFlex overflowed when adding a longer text to any of the toasts type but normal

### ISSUE THREAD

**Issue by toniremi** [fayaz07/ots#39]
When adding a longer text to the toast for any type with an icon (any type but normal) the widget gets a RenderFlex overflowed error and the text overflows on the right side of the toast.

To replicate simply add a text longer than 50 characters in length to any toast of type info, error, warning or success.

**Here are some screenshots that may show this with better detail:**

<img alt="error_toast_render_overflow" src="https://user-images.githubusercontent.com/1259874/132291589-ae7b1246-a8a1-4061-bc9f-a288c7d987c0.png"  width="30%"/> | <img alt="warning_toast_render_overflow" src="https://user-images.githubusercontent.com/1259874/132291622-058199f3-7399-45be-a5a6-0cadd081d67f.png"   width="30%"/>

**Here it is how this same text looks on the normal toast:**

<img alt="normal_tost_no_overflow" src="https://user-images.githubusercontent.com/1259874/132291654-ee8cbb77-454d-4a2d-97af-2e892ffb528d.png"  width="30%"/>

I am working on a solution already and may send a pull request once solved but I wanted to open issue just in case to keep track of it.

**Comment by fayaz07** [comment]
Thanks @toniremi
